export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCT_DETAILS = 'GET_PRODUCT_DETAILS'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_ERRORS = 'GET_ERRORS'
export const ADD_TO_BASKET = 'ADD_TO_BASKET'
export const DELETE_BASKET = 'DELETE_BASKET'
export const CHANGE_AMOUNT = 'CHANGE_AMOUNT'
export const CLEAR_CART = 'CLEAR_CART'

 